{% set name = "xarray-enmap" %}
{% set version = "0.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcdev/xarray-enmap/archive/v{{ version }}.tar.gz
  sha256: f16950d7b7b62db40876aaac81b8f28969aee466b23c29fd7b88872aea4f96e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.3
    - pip
  run:
    - python >={{ python_min }}
    - fsspec
    - rioxarray
    - shapely
    - xarray

test:
  imports:
    - xarray_enmap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/bcdev/xarray-enmap
  summary: xarray backend for EnMAP data archives
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
